<?php

namespace HostAndGuestBundle\Repository;

/**
 * experienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class experienceRepository extends \Doctrine\ORM\EntityRepository
{
}
