<?php

namespace HostAndGuestBundle\Repository;

/**
 * jaimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jaimeRepository extends \Doctrine\ORM\EntityRepository
{
}
