<?php

namespace HostAndGuestBundle\Repository;

/**
 * KristouRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KristouRepository extends \Doctrine\ORM\EntityRepository
{
}
